<Project Sdk="MSTest.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AwesomeAssertions" />
		<PackageReference Include="Repl.Testing" />
		<PackageReference Update="MSTest.TestFramework" VersionOverride="4.3.2" />
		<PackageReference Update="MSTest.TestAdapter" VersionOverride="4.3.2" />
		<PackageReference Update="Microsoft.Testing.Extensions.CodeCoverage" VersionOverride="18.9.0" />
		<PackageReference Update="Microsoft.Testing.Extensions.TrxReport" VersionOverride="2.3.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ManicTimeMcp\ManicTimeMcp.csproj" />
	</ItemGroup>

</Project>
